# Generated by Django 4.1.7 on 2023-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fichier_cv', models.FileField(upload_to='photos')),
                ('fichier_photo', models.FileField(upload_to='photos')),
                ('lien_prv', models.TextField()),
            ],
        ),
    ]
