# Generated by Django 4.1.7 on 2023-04-17 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyProd', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellai', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 17, 17, 24, 12, 916168))),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('acheve', models.CharField(max_length=1)),
                ('fichier', models.FileField(upload_to='photos')),
                ('Equipe', models.CharField(max_length=25)),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyProd.service')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='Equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyProd.equipe'),
        ),
    ]
