# Generated by Django 4.1.7 on 2023-04-18 12:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artyProd', '0003_equipe_projet_personnel_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 18, 13, 57, 45, 357874)),
        ),
    ]
