# Generated by Django 4.1.7 on 2023-04-19 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyProd', '0004_personnel_user_alter_projet_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 13, 38, 45, 650769)),
        ),
        migrations.CreateModel(
            name='Projett',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellai', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 13, 38, 45, 652768))),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('acheve', models.CharField(max_length=1)),
                ('fichier', models.FileField(upload_to='photos')),
                ('Equipe', models.CharField(max_length=25)),
                ('pdf', models.FileField(upload_to='fichier')),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyProd.service')),
            ],
        ),
    ]
