# Generated by Django 4.1.7 on 2023-04-19 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyProd', '0007_alter_projet_date_debut_alter_projett_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 15, 56, 46, 758193)),
        ),
        migrations.AlterField(
            model_name='projett',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 15, 56, 46, 759189)),
        ),
        migrations.AlterField(
            model_name='projett',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
