# Generated by Django 4.1.7 on 2023-04-19 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyProd', '0008_alter_projet_date_debut_alter_projett_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 19, 30, 47, 55478)),
        ),
        migrations.AlterField(
            model_name='projett',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 19, 30, 47, 56478)),
        ),
    ]
