# Generated by Django 4.1.7 on 2023-05-07 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyProd', '0010_alter_personnel_fichier_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('msg', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 7, 11, 16, 14, 447875)),
        ),
        migrations.AlterField(
            model_name='projett',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 7, 11, 16, 14, 448874)),
        ),
    ]
